config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_overriden/registration',
    sessions: 'devise_overriden/session'
  }

  devise_scope :user do
    authenticated :user do
      root 'administration/conditional_appointments#index', as: :root
    end

    unauthenticated do
      root 'landing#index', as: :unauthenticated_root
    end
  end

  get 'article/:id', to: 'administration/articles#show', as: 'show_article'
  get 'conditional_appointments/new',
      to: 'administration/conditional_appointments#new',
      as: 'new_conditional_appointment'

  scope 'admin', module: :administration do
    resources :users, only: [:new, :create]
    resources :patients, except: [:new, :edit] do
      get 'change_status', on: :member

      resources :personal_cards, only: [:index]
    end

    resources :doctors, except: [:new, :edit] do
      get 'manage_status', on: :member
      get 'determine_doctor_time', on: :collection
    end

    resources :appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :conditional_appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :price_list_categories, only: [:index, :create, :update, :destroy]
    resources :age_types, except: [:new, :edit, :show]
    resources :videos, except: :show
    resources :articles, except: :show
    resources :procedures, except: [:new, :edit, :show]

    resources :personal_cards, only: [:edit, :update] do
      get 'history/:id', on: :collection,
                         to: 'personal_cards#history', as: 'history'
    end

    resources :treatments do
      get 'add_primary_fields', on: :collection
      get 'invoice/:treatment_id', on: :collection, to: 'treatments#invoice', as: 'invoice'
      get 'details', on: :member
      get 'manage_state', on: :member
      patch 'manage_treatment_statuses', on: :member
    end

    get 'by_types', to: 'searches#by_types'

    resources :feedbacks, only: [:index, :create] do
      get 'update_status/:id', on: :collection, to: 'feedbacks#update_status', as: :update_status
    end

    resources :calendar, only: :index do
      get 'events', on: :collection
    end
    resources :messages do
      post 'delivery', on: :collection
    end
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient

  enum status: [:not_approved, :approved, :postponed, :canceled]

  validates_presence_of :doctor_id, :patient_id, :appointment_date, :start_time

  def self.appointment_participants(member)
    doctors = Doctor.includes(:user)
    patients = Patient.includes(:user)

    if member.kind_of? Doctor
      array = doctors.map {|doctor| {(doctor.name + ' ' + doctor.surname) => doctor.id }}
    elsif member.kind_of? Patient
      array = patients.map {|patient| {(patient.name + ' ' + patient.surname) => patient.id }}
    end

    if array != []
      array.inject(:merge)
    else
      []
    end
  end

end

app/controllers/administration/admin_controller.rb
class Administration::AdminController < ApplicationController
  before_action :authenticate_user

  private

  def authenticate_user
    if current_user.present?
      unless current_user.has_role? :admin or current_user.has_role? :doctor
        redirect_to_root
      end

    elsif current_user.nil?
      redirect_to_root
    end
  end

  def result_redirects(result, path, message)
    if result and message and path
      redirect_to path
      show_result_message message

    elsif message.nil?
      redirect_to path

    elsif path.nil? and message.present?
      redirect_to :back
      show_result_message message
    end
  end

  def redirect_to_root
    redirect_to root_path
    flash[:error] = 'У Вас нет доступа к данной странице'
  end

  def show_result_message message
    message[:success].present? ? flash[:success] = message[:success] : flash[:error] = message[:error]
  end

end

app/controllers/administration/age_types_controller.rb
module Administration
  class AgeTypesController < AdminController

    def index
      @age_types = AgeType.all.order(title: :asc) if AgeType.any?
      @age_type = AgeType.new
    end

    def create
      result = AgeTypes::Create.call(permitted_params: permitted_params)
      result_redirects(result, age_types_path, result.message)
    end
    def new

    end

    def update
      result = AgeTypes::Update.call(
        age_type_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, age_types_path, result.message)
    end

    def destroy
      result = AgeTypes::Destroy.call(age_type_id: params[:id])
      result_redirects(result, age_types_path, result.message)
    end

    private

      def permitted_params
        params.permit :title, :lower_age, :upper_age
      end

  end
end

app/controllers/administration/appointments_controller.rb
module Administration
  class AppointmentsController < AdminController

    def index
      result = Appointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @appointments = result.resources
      @appointment = Appointment.new
      @user = User.new
    end
    def edit
      @appointment = Appointment.find(params[:id])
    end

    def new
      @appointment = Appointment.new
    end

    def create
      result = Appointments::Create.call(permitted_params: permitted_params)
      result_redirects(result, appointments_path, result.message)
    end

    def update
      result = Appointments::Update.call(
        appointment_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = Appointments::Destroy.call(appointment_id: params[:id])
      result_redirects(result, appointments_path, result.message)
    end

    def change_status
      result = Appointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, appointments_path, result.message)
    end

    private

    def app_params
      params.permit :doctor_id, :patient_id, :appointment_date,
                    :utf8, :authenticity_token, :commit,
                    appointment: [:start_time, :status]
    end

    def permitted_params
      app_params[:appointment].merge(
        doctor_id: params[:doctor_id],
        patient_id: params[:patient_id],
        appointment_date: params[:appointment_date]
      )
    end

  end
end

app/controllers/administration/articles_controller.rb
module Administration
  class ArticlesController < AdminController
    before_action :authenticate_user, except: :show

    def index
      all_articles = current_user.doctor? ? current_user.doctor.articles : Article
      @articles = all_articles.order(created_at: :desc)
      @article = Article.new
    end

    def create
      @article = Article.new article_params
      if @article.save
        redirect_to articles_path
        flash[:success] = 'Статья успешно создана'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при создании статьи'
      end
    end

    def show
      @article = Article.find params[:id]
    end

    def update
      @article = Article.find params[:id]
      if @article.update! article_params
        redirect_to articles_path
        flash[:success] = 'Статья успешно обновлена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при обновлении статьи'
      end
    end

    def destroy
      article = Article.find params[:id]
      if article.destroy
        redirect_to articles_path
        flash[:success] = 'Статья успешно удалена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при удалении статьи'
      end
    end

    private

    def article_params
      params.permit :title, :content, :doctor_id, :image
    end
  end
end

app/controllers/administration/calendar_controller.rb
module Administration
  class CalendarController < AdminController

    def index
    end

    def events
      if current_user.admin?
        if params[:doctor_id].present?
          @treatments = Treatment.where(doctor_id: params[:doctor_id])
        else
          @treatments = Treatment.where.not(doctor_id: nil)
        end

      elsif current_user.doctor?
        @treatments = current_user.doctor.treatments
      end

      render json: fetch_events
    end

    private

    def fetch_events
      events = []
      @treatments.each do |treatment|
        events.push({
                        title: treatment.patient.fullname + "\n"+ treatment.doctor.fullname,
                        start: treatment.treatment_start,
                        end: treatment.treatment_end,
                        id: treatment.id,
                        backgroundColor: '#CCB0C9',
                        attribute: 'calendar_event'
                    })
      end

      events
    end
  end
end

app/controllers/administration/conditional_appointments_controller.rb
module Administration
  class ConditionalAppointmentsController < AdminController
    before_action :authenticate_user, only: [:index, :edit, :update, :destroy]

    def index
      result = ConditionalAppointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @conditional_apps = result.resources
      @appointment = Appointment.new
      @user = User.new
    end

    def new
      @conditional_app = ConditionalAppointment.new
    end

    def edit
      @conditional_app = ConditionalAppointment.find(params[:id])
    end

    def create
      result = ConditionalAppointments::Create.call(permitted_params: conditional_appointment_params)
      result_redirects(result, root_path, result.message)
    end

    def update
      result = ConditionalAppointments::Update.call(
          conditional_app_id: params[:id],
          user_params: user_params,
          patient_params: patient_params,
          appointment_params: appointment_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = ConditionalAppointments::Destroy.call(conditional_app_id: params[:id])
      result_redirects(result, conditional_appointments_path, result.message)
    end

    def change_status
      result = ConditionalAppointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, conditional_appointments_path, result.message)
    end

    private

    def permitted_params
      params.permit :name, :surname, :phone, :age, :doctor_id, :appointment_date,
                    :utf8, :authenticity_token, :commit, :action,
                    conditional_appointment: [:start_time, :email]
    end

    def user_params
      {
        'email' => permitted_params[:conditional_appointment][:email],
        'name' => permitted_params[:name],
        'surname' => permitted_params[:surname]
      }
    end

    def patient_params
      {
        'phone' => permitted_params[:phone],
        'age' => permitted_params[:age]
      }
    end

    def appointment_params
      permitted_params[:conditional_appointment].except(:email).
          merge(
              'doctor_id' => permitted_params[:doctor_id],
              'appointment_date' => permitted_params[:appointment_date]
          )
    end

    def conditional_appointment_params
      user_params.merge('phone' => permitted_params[:phone])
    end

  end
end

app/controllers/administration/doctors_controller.rb
module Administration
  class DoctorsController < AdminController

    def index
      result = Doctors::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page]
      )

      @doctors = result.resources
      @doctor = Doctor.new
    end

    def new
      @doctor = Doctor.new
    end

    def edit
      @doctor = Doctor.find(params[:id])
    end

    def show
      @doctor = Doctor.find(params[:id])
      @today_appointments = today_appointments(@doctor)
    end

    def create
      result = Doctors::Create.call(
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def update
      result = Doctors::Update.call(
        doctor_id: params[:id],
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def destroy
      result = Doctors::Destroy.call(doctor_id: params[:id])
      result_redirects(result, doctors_path, result.message)
    end

    def manage_status
      result = Doctors::ManageStatus.call(
        doctor_id: params[:id],
        work_status: params[:work_status]
      )

      result_redirects(result, doctors_path, result.message)
    end

    def determine_doctor_time
      result = Treatments::DetermineDoctorTime.call(
        doctor_id: params[:doctor_id],
        treatment_date: params[:date]
      )
       
      render json: result.resource
    end

    private

      def permitted_params
        params.permit :name, :surname, :phone,
                      doctor: [:position, :work_history, :work_experience, :work_status,
                               user_attributes: [:email, :avatar, :avatar_cache]]
      end

      def doctor_params
        permitted_params[:doctor].except(:user_attributes).
            merge('phone' => permitted_params[:phone])
      end

      def user_params
        permitted_params[:doctor][:user_attributes].
            merge(
                'name' => permitted_params[:name],
                'surname' => permitted_params[:surname]
            )
      end

      def today_appointments(doctor)
        doctor.appointments.where(appointment_date: :today)
      end

  end
end

app/controllers/administration/feedbacks_controller.rb
module Administration
  class FeedbacksController < AdminController
    skip_before_action :authenticate_user, only: :create

    def index
      @feedbacks = Feedback.all
    end

    def create
      @feedback = Feedback.create(feedback_params)
      if @feedback.save
        flash[:success] = "Ваше сообщение успешно отправлено"
        redirect_to root_path
      else
        flash[:error] = "Вы не заполнили обязательные поля"
        redirect_to root_path + '#contacts'
      end

    end

    def update_status
      @feedback = Feedback.find(params[:id])
      @feedback.update_status!

      redirect_to feedbacks_path
      flash[:success] = "Статус успешно обновлен"
    end

    private

    def feedback_params
      params.permit :name, :phone, :email, :message
    end

  end
end

app/controllers/administration/messages_controller.rb
module Administration
  class MessagesController < AdminController
    include MessagesHelper

    def index
      @message = Message.new
      @messages = Message.all.order(created_at: :desc)
      @patients = Patient.all
    end

    def create
      @message = Message.create(messages_params)
      response = @message.send_custom_sms
      @message.update(sms_id: @message.id.to_s.rjust(7, 'D00000'), send_time: Time.now, status: :sent) if response == '0' || response == '11'
      nikita_response response
      redirect_to messages_path
    end

    def delivery
      patients_ids = params[:patient]
      message = params[:text]
      if patients_ids.include?('all')
        patients = Patient.all
        patients_ids = patients.pluck(:id)
        phones = patients.pluck(:phone)
      else
        phones = Patient.where(id: patients_ids).pluck(:phone)
      end
      @delivery = Delivery.create(patient_ids: patients_ids, message: message)
      if @delivery.save
        response = @delivery.send_delivery_sms phones
        nikita_response response
      end
      redirect_to messages_path
    end

    private

    def messages_params
      params.permit :phone, :text
    end
  end
end

app/controllers/administration/personal_cards_controller.rb
module Administration
  class PersonalCardsController < AdminController

    def index
      patient = Patient.find params[:patient_id]
      @personal_card = patient.personal_card
      @treatments = patient.treatments
    end

    def edit
      @personal_card = PersonalCard.find(params[:id])
    end

    def update
      result = PersonalCards::Update.call(
        personal_card_id: params[:id],
        personal_card_params: permitted_params
      )

      result_redirects(result, patient_personal_cards_path(result.resource.patient), result.message)
    end

    def history
      patient = Patient.find params[:id]
      personal_card = patient.personal_card
      output = CardHistory.new(patient, personal_card)
      send_data output.render, :type => 'application/pdf', :filename => "personal_card.pdf", :disposition => "inline"
    end

    private

      def permitted_params
        params.require(:personal_card).permit :disease, :allergy, :medicine, :bleeding,
                      :pregnancy, :gestational_age, :patient_id
      end

  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

  def show_statuses_of appointment
    if appointment.not_approved?
      return ['gray', 'Не подтвержден']
    elsif appointment.approved?
      return ['green', 'Подтвержден']
    elsif appointment.postponed?
      return ['red', 'Отложен']
    elsif appointment.canceled?
      return ['black', 'Отменен']
    end
  end

  def appointments_amount
    current_user.doctor? ? current_user.doctor.appointments.count : Appointment.all.count
  end

end

app/views/administration/appointments/_appointments_index_table.html.erb
<table class="ui selectable celled black table" id="centred_table">
  <tr class="table_title">
    <th>Статус</th>
    <th>№</th>
    <%= render partial: 'administration/appointments/sorting/by_patient_surname' %>
    <th>E-mail</th>

    <% if current_user.admin? %>
        <%= render partial: 'administration/appointments/sorting/by_doctor_surname' %>
    <% elsif current_user.doctor? %>
        <th>Возраст</th>
    <% end %>

    <%= render partial: 'administration/appointments/sorting/by_appointment_date' %>

    <% if current_user.admin? %>
        <th colspan="4", class="centred_for_two_cells">Действия</th>
    <% end %>
  </tr>

  <% counter = 0 %>

  <% unless @appointments.nil? %>
      <% @appointments.each do |appointment| %>
          <tr>
            <td class="middle aligned">
              <% status = show_statuses_of appointment %>
              <div class="ui <%= status[0] %> ribbon label"><%= status[1] %></div>
            </td>

            <td class="middle aligned"><%= counter += 1 %></td>

            <td class="middle aligned" style="padding: 6px">
              <h4 class="ui image header">
                <% if appointment.patient.avatar.file.nil? %>
                    <img src="<%= asset_path appointment.patient.default_image %>" class="ui mini rounded image">
                <% else %>
                    <%= image_tag patient.avatar.tiny, class: "ui mini rounded image" %>
                <% end %>

                <div class="content">
                  <%= link_to appointment.patient.fullname, patient_path(appointment.patient) %>
                  <div class="sub header"><%= appointment.patient.phone %></div>
                </div>
              </h4>
            </td>

            <td>
              <% email = appointment.patient.email %>
              <%= email.present? ? email : 'Отсутствует' %>
            </td>

            <% if current_user.admin? %>
                <td class="middle aligned" style="padding: 6px">
                  <h4 class="ui image header">
                    <div class="content">
                      <%= link_to appointment.doctor.fullname, doctor_path(appointment.doctor) %>
                      <div class="sub header"><%= appointment.doctor.phone %></div>
                    </div>
                  </h4>
                </td>
            <% elsif current_user.doctor? %>
                <% age = appointment.patient.age.present? ? appointment.patient.age : 'Не указан' %>
                <td class="middle aligned"><%= age %></td>
            <% end %>

            <td class="middle aligned" style="padding: 6px">
              <h4 class="ui image header">
                <div class="content">
                  <%= l appointment.appointment_date, format: ("%d %B %Y") %>
                  <div class="sub header">
                    <%= "#{appointment.start_time.strftime('%H:%M')}" %>
                  </div>
                </div>
              </h4>
            </td>

            <% if current_user.admin? %>
                <%= render partial: 'administration/appointments/statuses', locals: {appointment: appointment} %>
                <td class="middle aligned"><%= link_to edit_appointment_path(appointment) do %>
                      <i class="write icon width_color_changed large"></i>
                  <% end %>
                </td>

                <td class="middle aligned"><%= link_to appointment_path(appointment),
                                                       data: {confirm: "Вы уверены что хотите удалить первичный осмотр из системы?"},
                                                       method: :delete do %>
                      <i class="trash icon width_color_changed large"></i>
                  <% end %>
                </td>

                <td class="middle aligned"><%= link_to new_treatment_path(patient_id: appointment.patient.id) do %>
                      <b>Создать прием</b>
                  <% end %>
                </td>
            <% end %>

          </tr>
      <% end %>
  <% end %>
</table>

<%= paginate @appointments, :remote => true %>

app/views/administration/appointments/_appointments_search_field.html.erb
<div class="right menu">
  <div class="item" id="item_right_padding">
    <div class="ui action input">
      <%= form_tag url_for(:controller => 'administration/searches', :action => 'by_types'), method: "get", remote: true do %>
          <%= hidden_field_tag :search_type, 'appointments' %>
          <%= text_field_tag :search_query, params[:search_query], placeholder: "Поиск..." %>
      <% end %>
    </div>
  </div>
</div>

app/views/administration/appointments/_form_for_appointment.html.erb
<div class="ui form width changed" id="second_datepicker_identifier_on_page" %>
  <div class="create_appointment_for_existing_patient">
      <% @appointment.build_doctor if @appointment.doctor.nil? %>
      <% @appointment.build_patient if @appointment.patient.nil? %>
      <%= form_for(@appointment, html: {class: 'ui equal width form'}) do |f| %>

          <div class="two fields">
            <div class="field">
              <label>Доктор</label>
              <%= f.select :doctor_id, Appointment.appointment_participants(@appointment.doctor),
                           {prompt: yield(:doctor_prompt) },
                           {class: 'ui search fluid dropdown', name: 'doctor_id'} %>
            </div>

            <div class="field">
              <label>Пациент</label>
              <%= f.select :patient_id, Appointment.appointment_participants(@appointment.patient),
                           {prompt: yield(:patient_prompt) },
                           {class: 'ui search fluid dropdown', name: 'patient_id'} %>
            </div>
          </div>

          <div class="two fields">
            <div class="field">
              <label>Дата осмотра</label>
              <%= f.text_field :appointment_date,
                               'data-provide' => 'datepicker',
                               :value=>"#{f.object.appointment_date.strftime("%d %B %Y") unless f.object.new_record?}",
                               placeholder: yield(:date_placeholder),
                               name: 'appointment_date' %>
            </div>

            <div class="field">
              <label>Время</label>
              <%= f.time_select :start_time, {start_hour: 8, end_hour: 18, minute_step: 15}, {class: 'ui search dropdown'} %>
            </div>
          </div></br>

          <div class="ui buttons", id="edit_form_style">
            <%= f.submit yield(:button), class: "ui blue button" %>
            <div class="or"></div>
            <%= link_to 'Вернуться к списку', appointments_path, class: "ui negative button" %>
          </div>

      <% end %>
  </div>
</div>

app/views/administration/appointments/_modal_for_creating_appointment.html.erb
<button type="button" class="ui blue button" data-toggle="modal" data-target="#new_appointment" style="margin-right: 15px">
  <i class="add user icon"></i>
  Создать новый осмотр
</button>

<div class="modal fade" id="new_appointment" tabindex="-1" role="dialog" aria-labelledby="new_appointmentLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <%= render '/administration/users/new' %>
      </div>

      <div class="modal-footer">
        <button type="button" class="ui gray button" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

app/views/administration/appointments/_statuses.html.erb
<td class="middle aligned">
  <div class="dropdown_center_showing">
    <div class="ui dropdown">
        <i class="options icon width_color_changed large"></i>
        <div class="menu">
          <div class="header">
            <i class="tags icon"></i>
            Статус первичного осмотра
          </div>

          <div class="scrolling menu">
            <%= link_to change_status_appointment_path(appointment, status: 'not_approved'), class: 'item' do %>
                <div class="ui gray empty circular label"></div>
                Не подтвержден
            <% end %>

            <%= link_to change_status_appointment_path(appointment, status: 'approved'), class: 'item' do %>
                <div class="ui green empty circular label"></div>
                Подтвержден
            <% end %>

            <%= link_to change_status_appointment_path(appointment, status: 'postponed'), class: 'item' do %>
                <div class="ui red empty circular label"></div>
                Отложен
            <% end %>

            <%= link_to change_status_appointment_path(appointment, status: 'canceled'), class: 'item' do %>
                <div class="ui black empty circular label"></div>
                Отменен
            <% end %>
          </div>

        </div>
      </div>
  </div>
</td>

app/views/administration/appointments/edit.html.erb
<div class="ui form width changed" id="datepicker_identifier">
  <% @appointment.build_doctor if @appointment.doctor.nil? %>
  <% @appointment.build_patient if @appointment.patient.nil? %>
  <%= form_for(@appointment, html: {class: 'ui equal width form'}) do |f| %>

      <h4 class="ui dividing header"><%= 'Редактирование первичного осмотра' %></h4></br>

      <div class="two fields">
        <div class="field">
          <label>Доктор</label>
          <%= f.select :doctor_id, Appointment.appointment_participants(@appointment.doctor),
                       {prompt: yield(:doctor_prompt) },
                       {class: 'ui search fluid dropdown', name: 'doctor_id'} %>
        </div>

        <div class="field">
          <label>Пациент</label>
          <%= f.select :patient_id, Appointment.appointment_participants(@appointment.patient),
                       {prompt: yield(:patient_prompt) },
                       {class: 'ui search fluid dropdown', name: 'patient_id'} %>
        </div>
      </div>

      <div class="two fields">
        <div class="field">
          <label>Дата осмотра</label>
          <%= f.text_field :appointment_date,
                           'data-behaviour' => 'datepicker',
                           data: {date_format: 'dd/mm/yyyy'},
                           :value=>"#{f.object.appointment_date.strftime("%d %B %Y") unless f.object.new_record?}",
                           placeholder: yield(:date_placeholder),
                           name: 'appointment_date' %>
        </div>

        <div class="field">
          <label>Время</label>
          <%= f.time_select :start_time, {start_hour: 8, end_hour: 18, minute_step: 15}, {class: 'ui search dropdown'} %>
        </div>
      </div><br>

      <div class="ui buttons", id="edit_form_style">
        <%= f.submit 'Обновить данные', class: "ui blue button" %>
        <div class="or"></div>
        <%= link_to 'Вернуться к списку', appointments_path, class: "ui negative button" %>
      </div>

  <% end %>
</div>

<script>
    $(function () {
        $('.ui.form.width.changed').form({
            fields: {
                doctor : { identifier: 'doctor_id',
                    rules: [{ type: 'empty', prompt: 'Выберите одного из докторов' }]
                },

                patient : { identifier: 'patient_id',
                    rules: [{ type: 'empty', prompt: 'Выберите одного из пациентов' }]
                },


                date : { identifier: 'appointment_date',
                    rules: [{ type: 'empty', prompt: 'Заполните дату ' }]
                }
            },
            inline : true,
            on     : 'blur',
        })
    })
</script>

app/views/administration/appointments/index.html.erb
<h3 class="ui left floated header">Список первичных осмотров</h3>

<div class="ui right floated header">
  <div class="all_database_records_count">
    Всего записей: <b><%= appointments_amount %></b>
  </div>
</div>

<div class="ui dividing header"></div>

<div class="ui secondary  menu">
  <div class="left menu">
    <div class="item" id="item_left_padding">
      <% if current_user.admin? %>
          <%= render 'administration/appointments/modal_for_creating_appointment' %>
      <% end %>

      <%= link_to conditional_appointments_path, class: 'ui blue button' do %>
          <i class="checkmark box icon"></i>
            Предварительные записи
          <div class="floating ui red circular label">
            <%= conditional_appointments_amount %>
          </div>
      <% end %>
    </div>
  </div>

  <%= render 'administration/appointments/appointments_search_field' %>
</div>

<div class="after_search_rendered_table">
    <%= render 'administration/appointments/appointments_index_table' %>
</div>

<% if @appointments.empty? %>
    <h4 class="ui red block header">
      На данный момент нет первичных осмотров
    </h4>
<% end %>

<%= alertify_flash %>

app/views/administration/appointments/index.js.erb
$('.after_search_rendered_table').html("<%= j render partial: 'administration/appointments/appointments_index_table' %>");

$(document).ready(function () {
    $('.ui.checkbox').checkbox();
    $('.ui.dropdown').dropdown();
    $('.ui.accordion').accordion();
    $('.secondary.menu .item').tab();
});

app/views/administration/appointments/new.html.erb
<%= render 'administration/appointments/form_for_appointment' %>

<% provide(:button, 'Создать осмотр') %>
<% provide(:message, 'Создание первичного осмотра пациента') %>
<% provide(:doctor_prompt, 'Выберите доктора для осмотра') %>
<% provide(:patient_prompt, 'Выберите пациента') %>
<% provide(:date_placeholder, 'Дата осмотра') %>