config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_overriden/registration',
    sessions: 'devise_overriden/session'
  }

  devise_scope :user do
    authenticated :user do
      root 'administration/conditional_appointments#index', as: :root
    end

    unauthenticated do
      root 'landing#index', as: :unauthenticated_root
    end
  end

  get 'article/:id', to: 'administration/articles#show', as: 'show_article'
  get 'conditional_appointments/new',
      to: 'administration/conditional_appointments#new',
      as: 'new_conditional_appointment'

  scope 'admin', module: :administration do
    resources :users, only: [:new, :create]
    resources :patients, except: [:new, :edit] do
      get 'change_status', on: :member

      resources :personal_cards, only: [:index]
    end

    resources :doctors, except: [:new, :edit] do
      get 'manage_status', on: :member
      get 'determine_doctor_time', on: :collection
    end

    resources :appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :conditional_appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :price_list_categories, only: [:index, :create, :update, :destroy]
    resources :age_types, except: [:new, :edit, :show]
    resources :videos, except: :show
    resources :articles, except: :show
    resources :procedures, except: [:new, :edit, :show]

    resources :personal_cards, only: [:edit, :update] do
      get 'history/:id', on: :collection,
                         to: 'personal_cards#history', as: 'history'
    end

    resources :treatments do
      get 'add_primary_fields', on: :collection
      get 'invoice/:treatment_id', on: :collection, to: 'treatments#invoice', as: 'invoice'
      get 'details', on: :member
      get 'manage_state', on: :member
      patch 'manage_treatment_statuses', on: :member
    end

    get 'by_types', to: 'searches#by_types'

    resources :feedbacks, only: [:index, :create] do
      get 'update_status/:id', on: :collection, to: 'feedbacks#update_status', as: :update_status
    end

    resources :calendar, only: :index do
      get 'events', on: :collection
    end
    resources :messages do
      post 'delivery', on: :collection
    end
  end
end

app/controllers/administration/admin_controller.rb
class Administration::AdminController < ApplicationController
  before_action :authenticate_user

  private

  def authenticate_user
    if current_user.present?
      unless current_user.has_role? :admin or current_user.has_role? :doctor
        redirect_to_root
      end

    elsif current_user.nil?
      redirect_to_root
    end
  end

  def result_redirects(result, path, message)
    if result and message and path
      redirect_to path
      show_result_message message

    elsif message.nil?
      redirect_to path

    elsif path.nil? and message.present?
      redirect_to :back
      show_result_message message
    end
  end

  def redirect_to_root
    redirect_to root_path
    flash[:error] = 'У Вас нет доступа к данной странице'
  end

  def show_result_message message
    message[:success].present? ? flash[:success] = message[:success] : flash[:error] = message[:error]
  end

end

app/controllers/administration/age_types_controller.rb
module Administration
  class AgeTypesController < AdminController

    def index
      @age_types = AgeType.all.order(title: :asc) if AgeType.any?
      @age_type = AgeType.new
    end

    def create
      result = AgeTypes::Create.call(permitted_params: permitted_params)
      result_redirects(result, age_types_path, result.message)
    end
    def new

    end

    def update
      result = AgeTypes::Update.call(
        age_type_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, age_types_path, result.message)
    end

    def destroy
      result = AgeTypes::Destroy.call(age_type_id: params[:id])
      result_redirects(result, age_types_path, result.message)
    end

    private

      def permitted_params
        params.permit :title, :lower_age, :upper_age
      end

  end
end

app/controllers/administration/appointments_controller.rb
module Administration
  class AppointmentsController < AdminController

    def index
      result = Appointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @appointments = result.resources
      @appointment = Appointment.new
      @user = User.new
    end
    def edit
      @appointment = Appointment.find(params[:id])
    end

    def new
      @appointment = Appointment.new
    end

    def create
      result = Appointments::Create.call(permitted_params: permitted_params)
      result_redirects(result, appointments_path, result.message)
    end

    def update
      result = Appointments::Update.call(
        appointment_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = Appointments::Destroy.call(appointment_id: params[:id])
      result_redirects(result, appointments_path, result.message)
    end

    def change_status
      result = Appointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, appointments_path, result.message)
    end

    private

    def app_params
      params.permit :doctor_id, :patient_id, :appointment_date,
                    :utf8, :authenticity_token, :commit,
                    appointment: [:start_time, :status]
    end

    def permitted_params
      app_params[:appointment].merge(
        doctor_id: params[:doctor_id],
        patient_id: params[:patient_id],
        appointment_date: params[:appointment_date]
      )
    end

  end
end

app/controllers/administration/articles_controller.rb
module Administration
  class ArticlesController < AdminController
    before_action :authenticate_user, except: :show

    def index
      all_articles = current_user.doctor? ? current_user.doctor.articles : Article
      @articles = all_articles.order(created_at: :desc)
      @article = Article.new
    end

    def create
      @article = Article.new article_params
      if @article.save
        redirect_to articles_path
        flash[:success] = 'Статья успешно создана'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при создании статьи'
      end
    end

    def show
      @article = Article.find params[:id]
    end

    def update
      @article = Article.find params[:id]
      if @article.update! article_params
        redirect_to articles_path
        flash[:success] = 'Статья успешно обновлена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при обновлении статьи'
      end
    end

    def destroy
      article = Article.find params[:id]
      if article.destroy
        redirect_to articles_path
        flash[:success] = 'Статья успешно удалена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при удалении статьи'
      end
    end

    private

    def article_params
      params.permit :title, :content, :doctor_id, :image
    end
  end
end

app/controllers/administration/calendar_controller.rb
module Administration
  class CalendarController < AdminController

    def index
    end

    def events
      if current_user.admin?
        if params[:doctor_id].present?
          @treatments = Treatment.where(doctor_id: params[:doctor_id])
        else
          @treatments = Treatment.where.not(doctor_id: nil)
        end

      elsif current_user.doctor?
        @treatments = current_user.doctor.treatments
      end

      render json: fetch_events
    end

    private

    def fetch_events
      events = []
      @treatments.each do |treatment|
        events.push({
                        title: treatment.patient.fullname + "\n"+ treatment.doctor.fullname,
                        start: treatment.treatment_start,
                        end: treatment.treatment_end,
                        id: treatment.id,
                        backgroundColor: '#CCB0C9',
                        attribute: 'calendar_event'
                    })
      end

      events
    end
  end
end

app/controllers/administration/conditional_appointments_controller.rb
module Administration
  class ConditionalAppointmentsController < AdminController
    before_action :authenticate_user, only: [:index, :edit, :update, :destroy]

    def index
      result = ConditionalAppointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @conditional_apps = result.resources
      @appointment = Appointment.new
      @user = User.new
    end

    def new
      @conditional_app = ConditionalAppointment.new
    end

    def edit
      @conditional_app = ConditionalAppointment.find(params[:id])
    end

    def create
      result = ConditionalAppointments::Create.call(permitted_params: conditional_appointment_params)
      result_redirects(result, root_path, result.message)
    end

    def update
      result = ConditionalAppointments::Update.call(
          conditional_app_id: params[:id],
          user_params: user_params,
          patient_params: patient_params,
          appointment_params: appointment_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = ConditionalAppointments::Destroy.call(conditional_app_id: params[:id])
      result_redirects(result, conditional_appointments_path, result.message)
    end

    def change_status
      result = ConditionalAppointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, conditional_appointments_path, result.message)
    end

    private

    def permitted_params
      params.permit :name, :surname, :phone, :age, :doctor_id, :appointment_date,
                    :utf8, :authenticity_token, :commit, :action,
                    conditional_appointment: [:start_time, :email]
    end

    def user_params
      {
        'email' => permitted_params[:conditional_appointment][:email],
        'name' => permitted_params[:name],
        'surname' => permitted_params[:surname]
      }
    end

    def patient_params
      {
        'phone' => permitted_params[:phone],
        'age' => permitted_params[:age]
      }
    end

    def appointment_params
      permitted_params[:conditional_appointment].except(:email).
          merge(
              'doctor_id' => permitted_params[:doctor_id],
              'appointment_date' => permitted_params[:appointment_date]
          )
    end

    def conditional_appointment_params
      user_params.merge('phone' => permitted_params[:phone])
    end

  end
end

app/controllers/administration/doctors_controller.rb
module Administration
  class DoctorsController < AdminController

    def index
      result = Doctors::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page]
      )

      @doctors = result.resources
      @doctor = Doctor.new
    end

    def new
      @doctor = Doctor.new
    end

    def edit
      @doctor = Doctor.find(params[:id])
    end

    def show
      @doctor = Doctor.find(params[:id])
      @today_appointments = today_appointments(@doctor)
    end

    def create
      result = Doctors::Create.call(
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def update
      result = Doctors::Update.call(
        doctor_id: params[:id],
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def destroy
      result = Doctors::Destroy.call(doctor_id: params[:id])
      result_redirects(result, doctors_path, result.message)
    end

    def manage_status
      result = Doctors::ManageStatus.call(
        doctor_id: params[:id],
        work_status: params[:work_status]
      )

      result_redirects(result, doctors_path, result.message)
    end

    def determine_doctor_time
      result = Treatments::DetermineDoctorTime.call(
        doctor_id: params[:doctor_id],
        treatment_date: params[:date]
      )
       
      render json: result.resource
    end

    private

      def permitted_params
        params.permit :name, :surname, :phone,
                      doctor: [:position, :work_history, :work_experience, :work_status,
                               user_attributes: [:email, :avatar, :avatar_cache]]
      end

      def doctor_params
        permitted_params[:doctor].except(:user_attributes).
            merge('phone' => permitted_params[:phone])
      end

      def user_params
        permitted_params[:doctor][:user_attributes].
            merge(
                'name' => permitted_params[:name],
                'surname' => permitted_params[:surname]
            )
      end

      def today_appointments(doctor)
        doctor.appointments.where(appointment_date: :today)
      end

  end
end

app/controllers/administration/feedbacks_controller.rb
module Administration
  class FeedbacksController < AdminController
    skip_before_action :authenticate_user, only: :create

    def index
      @feedbacks = Feedback.all
    end

    def create
      @feedback = Feedback.create(feedback_params)
      if @feedback.save
        flash[:success] = "Ваше сообщение успешно отправлено"
        redirect_to root_path
      else
        flash[:error] = "Вы не заполнили обязательные поля"
        redirect_to root_path + '#contacts'
      end

    end

    def update_status
      @feedback = Feedback.find(params[:id])
      @feedback.update_status!

      redirect_to feedbacks_path
      flash[:success] = "Статус успешно обновлен"
    end

    private

    def feedback_params
      params.permit :name, :phone, :email, :message
    end

  end
end

app/controllers/administration/messages_controller.rb
module Administration
  class MessagesController < AdminController
    include MessagesHelper

    def index
      @message = Message.new
      @messages = Message.all.order(created_at: :desc)
      @patients = Patient.all
    end

    def create
      @message = Message.create(messages_params)
      response = @message.send_custom_sms
      @message.update(sms_id: @message.id.to_s.rjust(7, 'D00000'), send_time: Time.now, status: :sent) if response == '0' || response == '11'
      nikita_response response
      redirect_to messages_path
    end

    def delivery
      patients_ids = params[:patient]
      message = params[:text]
      if patients_ids.include?('all')
        patients = Patient.all
        patients_ids = patients.pluck(:id)
        phones = patients.pluck(:phone)
      else
        phones = Patient.where(id: patients_ids).pluck(:phone)
      end
      @delivery = Delivery.create(patient_ids: patients_ids, message: message)
      if @delivery.save
        response = @delivery.send_delivery_sms phones
        nikita_response response
      end
      redirect_to messages_path
    end

    private

    def messages_params
      params.permit :phone, :text
    end
  end
end

app/controllers/administration/patients_controller.rb
module Administration
  class PatientsController < AdminController

    def index
      result = Patients::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page],
          current_user: current_user
      )

      @patients = result.resources
      @patient = Patient.new
    end

    def show
      @patient = Patient.find(params[:id])

      result = Treatments::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page],
          patient: @patient,
          current_user: current_user
      )

      @treatments = result.resources
    end

    def new
      @patient = Patient.new
    end

    def edit
      @patient = Patient.find(params[:id])
    end

    def create
      result = Patients::Create.call(
        user_params: user_params,
        patient_params: patient_params
      )

      result_redirects(result, patients_path, result.message)
    end

    def update
      result = Patients::Update.call(
          patient_id: params[:id],
          patient_params: patient_params,
          user_params: user_params
      )

      result_redirects(result, patients_path, result.message)
    end

    def destroy
      result = Patients::Destroy.call(patient_id: params[:id])
      result_redirects(result, patients_path, result.message)
    end

    def change_status
      result = Patients::ChangeStatus.call(patient_id: params[:id])
      result_redirects(result, patients_path, result.message)
    end

    private

    def permitted_params
      params.permit :phone, :age, :name, :surname,
                    patient: [:gender, user_attributes: [:email, :avatar, :avatar_cache]]
    end

    def patient_params
      permitted_params[:patient].except(:user_attributes).merge(
        'phone' => permitted_params[:phone],
        'age' => permitted_params[:age]
      )
    end

    def user_params
      permitted_params[:patient][:user_attributes].merge(
        'name' => permitted_params[:name],
        'surname' => permitted_params[:surname]
      )
    end

  end
end

app/views/administration/procedures/_edit.html.erb
<div class="ui form width changed">
  <div class="edit_procedure">
      <%= form_for(procedure, html: {class: 'ui equal width form'}) do |f| %>

          <h4 class="ui dividing header"><%= 'Редактирование процедуры' %></h4></br>

          <div class="two fields">
              <div class="field">
                <label>Наименование</label>
                <%= f.text_field :title, placeholder: 'Наименование категории', name: 'title' %>
              </div>

              <div class="field">
                <label>Категория</label>
                <%= f.collection_select :category_id, PriceListCategory.all, :id, :title,
                                        { prompt: "Выберите категорию"},
                                        {class: 'ui search fluid dropdown', name: 'category_id' }%>
              </div>
          </div>

          <% if procedure.age_types.present? %>
            <h5 class="ui dividing header">Стоимость процедуры по возрастным категориям</h5>
          <% end %>

          <% if procedure.age_types.present? %>
            <% procedure.procedure_age_types.each do |type| %>
                <div class="two fields">
                  <div class="field">
                    <%= select_tag 'prices[]age_type', options_from_collection_for_select(AgeType.all, "id", "title", type.age_type.id),
                                   {prompt: 'Выберите возрастную категорию', class: 'ui search fluid dropdown'}%>
                  </div>

                  <div class="field">
                    <%= text_field_tag 'prices[]price', nil, placeholder: 'Введите стоимость в цифрах',
                                       value: type.price.to_i %>
                  </div>
                </div>
            <% end %>
          <% end %>

          <% if procedure.age_types.count < AgeType.all.count %>
            <% (AgeType.all.count - procedure.age_types.count).times do %>
                <div class="two fields">
                  <div class="field">
                    <%= select_tag 'prices[]age_type', options_from_collection_for_select(AgeType.all, "id", "title"),
                                   {
                                           prompt: 'Выберите возрастную категорию',
                                           class: 'ui search fluid dropdown',
                                   } %>
                  </div>

                  <div class="field">
                    <%= text_field_tag 'prices[]price', nil, placeholder: 'Введите стоимость в цифрах' %>
                  </div>
                </div>
            <% end %>
          <% end %>

          <div class="ui buttons", id="edit_form_style">
            <%= f.submit 'Обновить процедуру', class: "ui blue button" %>
            <div class="or"></div>
            <%= link_to 'Вернуться к списку', procedures_path, class: "ui negative button" %>
          </div>

      <% end %>
  </div>
</div>

app/views/administration/procedures/_form_for_accordion.html.erb
<% if procedure.age_types.present? %>
    <td class="middle aligned list">
        <a class="title">
          <i class="icon dropdown"></i>
          <b><%= procedure.title %></b>
        </a>

      <div class="content">
        <div class="ui middle aligned list">
           <% if procedure.age_types %>
               <div class="item">
                  <div class="title" style="padding: 0em">
                    <div class="description" id="list_left_margin">
                      <% procedure.procedure_age_types.each do |type| %>
                          <div class="content">
                            <i class="angle double right icon"></i>
                            <% if type.age_type %>
                              <b><%= type.age_type.title %>:</b> &nbsp;<%= type.price.to_i %> сом
                            <% else %>
                                Не имеет возрастных категорий
                            <% end %>
                          </div>
                      <% end %>
                    </div>
                  </div>
               </div>
           <% end %>
        </div>
      </div>
    </td>
<% else %>
    <td class="middle aligned list">
      <b><%= procedure.title %></b>
    </td>
<% end %>

app/views/administration/procedures/_form_for_procedure.html.erb
<div class="ui form width changed">
  <div class="create_procedure">

    <%= form_for(@procedure, html: {class: 'ui equal width form'}) do |f| %>

      <h4 class="ui dividing header"><%= 'Создание процедуры' %></h4></br>

        <div class="two fields">
          <div class="field">
            <label>Наименование</label>
            <%= f.text_field :title, placeholder: 'Наименование процедуры', name: 'title' %>
          </div>

          <div class="field">
            <label>Категория</label>
            <%= f.collection_select :category_id, PriceListCategory.all, :id, :title,
                                    { prompt: "Выберите категорию"},
                                    {class: 'ui search fluid dropdown', name: 'category_id' }%>
          </div>
        </div>

      <h5 class="ui dividing header">Стоимость процедуры по возрастным категориям</h5>

      <% if AgeType.all.present? %>
        <div class="two fields">
          <div class="field">
            <%= select_tag 'prices[]age_type',
                           options_from_collection_for_select(AgeType.all.where(constant_name: 'adult'), "id", "title"),
                           {prompt: 'Выберите возрастную категорию',
                            class: 'ui search fluid dropdown',
                            name: 'age_type'} %>
          </div>

          <div class="field">
            <%= text_field_tag 'prices[]price', nil, placeholder: 'Введите стоимость в цифрах', name: 'price' %>
          </div>
        </div>

        <% quantity = AgeType.all.count - 1 %>
        <% quantity.times do %>
          <div class="two fields">
            <div class="field">
              <%= select_tag 'prices[]age_type', options_from_collection_for_select(AgeType.all.where(constant_name: nil), "id", "title"),
                                  {prompt: 'Выберите возрастную категорию',
                                   class: 'ui search fluid dropdown'} %>
            </div>

            <div class="field">
              <%= text_field_tag 'prices[]price', nil, placeholder: 'Введите стоимость в цифрах' %>
            </div>
          </div>
        <% end %>

      <% else %>
        <h6 class="ui red block header">
          Для создания процедуры вам необходимо создать <%= link_to 'возрастные категории', age_types_path %>
        </h6><br>
      <% end %>

      <div class="ui buttons", id="edit_form_style">
        <% if AgeType.all.present? %>
          <%= f.submit 'Создать процедуру', class: "ui blue button" %>
        <% else %>
          <%= f.submit 'Создать процедуру', class: "ui disabled blue button" %>
        <% end %>

        <div class="or"></div>
        <%= link_to 'Вернуться к списку', price_list_categories_path, class: "ui negative button" %>
      </div>

    <% end %>
  </div>
</div>

app/views/administration/procedures/_modal_for_creating_procedure.html.erb
<div class="left menu">
  <div class="item", id="item_left_padding">

    <button type="button" class="ui blue button" data-toggle="modal" data-target="#new_procedure">
      <i class="checkmark box icon"></i>
      Создать новую процедуру
    </button>

    <div class="modal fade" id="new_procedure" tabindex="-1" role="dialog" aria-labelledby="new_procedureLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-body">
            <%= render 'administration/procedures/form_for_procedure' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="ui gray button" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/administration/procedures/_modal_for_updating_procedure.html.erb
<div class="modal fade" id="update_procedure-<%= procedure.id %>" tabindex="-1" role="dialog" aria-labelledby="update_procedureLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <%= render partial: 'administration/procedures/edit', locals: {procedure: procedure} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="ui gray button" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

app/views/administration/procedures/_procedures_index_table.html.erb
<table class="ui selectable celled black table", id="centred_table">
  <tr class="table_title">
    <th>№</th>
    <%= render partial: 'administration/procedures/sorting/by_title' %>
    <th>Категория процедуры</th>
    <% if current_user.admin? %>
        <th colspan="2", class="centred_for_two_cells">Действия</th>
    <% end %>
  </tr>

  <% counter = 0 %>
  <% if @procedures %>
      <% @procedures.each do |procedure| %>
          <tr>
            <td class="middle aligned"><%= counter += 1 %></td>

            <%= render partial: 'administration/procedures/form_for_accordion', locals: {procedure: procedure} %>

            <td class="middle aligned"><%= procedure.category.title %></td>

            <% if current_user.admin? %>
                <td class="middle aligned">
                  <a href="#", data-toggle="modal" data-target="#update_procedure-<%= procedure.id %>">
                    <i class="write icon width_color_changed large"></i>
                  </a>

                  <%= render partial: 'administration/procedures/modal_for_updating_procedure', locals: {procedure: procedure} %>
                </td>

                <td class="middle aligned"><%= link_to procedure_path(procedure),
                                                       data: {confirm: "Вы уверены что хотите удалить процедуру: #{procedure.title}, из системы?"},
                                                       method: :delete do %>
                      <i class="trash icon width_color_changed large"></i>
                  <% end %>
                </td>
            <% end %>
          </tr>
      <% end %>
  <% end %>
</table>

<%= paginate @procedures, :remote => true %>

app/views/administration/procedures/_procedures_search_field.html.erb
<div class="right menu">
  <div class="item" id="item_right_padding">
    <div class="ui action input">
      <%= form_tag url_for(:controller => 'administration/searches', :action => 'by_types'), method: "get", remote: true do %>
          <%= hidden_field_tag :search_type, 'procedures' %>
          <%= text_field_tag :search_query, params[:search_query], placeholder: "Поиск..." %>
      <% end %>
    </div>
  </div>
</div>

app/views/administration/procedures/index.html.erb
<h3 class="ui left floated header">Процедуры по прейскуранту</h3>

<div class="ui right floated header">
  <div class="all_database_records_count">
    Всего записей: <b><%= Procedure.all.count %></b>
  </div>
</div>

<div class="ui dividing header"></div>

<div class="ui secondary menu">
  <% if current_user.admin? %>
      <%= render 'administration/procedures/modal_for_creating_procedure' %>
  <% end %>
  <%= render 'administration/procedures/procedures_search_field' %>
</div>

<div class="ui accordion field">
  <div class="after_search_rendered_table">
    <%= render 'administration/procedures/procedures_index_table' %>
  </div>
</div>

<% if @procedures.empty? %>
    <h4 class="ui red block header">
      На данный момент список процедур клиники пуст.
    </h4>
<% end %>

app/views/administration/procedures/index.js.erb
$('.after_search_rendered_table').html("<%= j render partial: 'administration/procedures/procedures_index_table' %>");

$(document).ready(function () {
    $('.ui.checkbox').checkbox();
    $('.ui.dropdown').dropdown();
    $('.ui.accordion').accordion();
    $('.secondary.menu .item').tab();
});