config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_overriden/registration',
    sessions: 'devise_overriden/session'
  }

  devise_scope :user do
    authenticated :user do
      root 'administration/conditional_appointments#index', as: :root
    end

    unauthenticated do
      root 'landing#index', as: :unauthenticated_root
    end
  end

  get 'article/:id', to: 'administration/articles#show', as: 'show_article'
  get 'conditional_appointments/new',
      to: 'administration/conditional_appointments#new',
      as: 'new_conditional_appointment'

  scope 'admin', module: :administration do
    resources :users, only: [:new, :create]
    resources :patients, except: [:new, :edit] do
      get 'change_status', on: :member

      resources :personal_cards, only: [:index]
    end

    resources :doctors, except: [:new, :edit] do
      get 'manage_status', on: :member
      get 'determine_doctor_time', on: :collection
    end

    resources :appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :conditional_appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :price_list_categories, only: [:index, :create, :update, :destroy]
    resources :age_types, except: [:new, :edit, :show]
    resources :videos, except: :show
    resources :articles, except: :show
    resources :procedures, except: [:new, :edit, :show]

    resources :personal_cards, only: [:edit, :update] do
      get 'history/:id', on: :collection,
                         to: 'personal_cards#history', as: 'history'
    end

    resources :treatments do
      get 'add_primary_fields', on: :collection
      get 'invoice/:treatment_id', on: :collection, to: 'treatments#invoice', as: 'invoice'
      get 'details', on: :member
      get 'manage_state', on: :member
      patch 'manage_treatment_statuses', on: :member
    end

    get 'by_types', to: 'searches#by_types'

    resources :feedbacks, only: [:index, :create] do
      get 'update_status/:id', on: :collection, to: 'feedbacks#update_status', as: :update_status
    end

    resources :calendar, only: :index do
      get 'events', on: :collection
    end
    resources :messages do
      post 'delivery', on: :collection
    end
  end
end

app/views/shared/_admin_navbar.html.erb
<%= link_to appointments_path, class: 'item' do %>
  <i class="first aid icon"></i>
  Первичные осмотры
<% end %>

<%= link_to patients_path, class: 'item' do %>
  <i class="users icon"></i>
  Пациенты
<% end %>

<%= link_to doctors_path, class: 'item' do %>
  <i class="doctor icon"></i>
  Доктора
<% end %>

<div class="menu">
  <div class="ui dropdown item">
    <i class="dollar icon"></i>
      Прейскурант
    <i class="dropdown icon"></i>

    <div class="menu">
      <%= link_to price_list_categories_path, class: 'item' do %>
        <i class="list layout icon"></i>
        <b>Категории</b>
      <% end %>

      <%= link_to procedures_path, class: 'item' do %>
        <i class="first aid icon"></i>
        <b>Процедуры</b>
      <% end %>

      <%= link_to age_types_path, class: 'item' do %>
        <i class="warning circle icon"></i>
        <b>Возраста</b>
      <% end %>
    </div>

  </div>
</div>

<div class="menu">
  <div class="ui dropdown item">
    <i class="info circle icon"></i>
      Дополнительно
    <i class="dropdown icon"></i>

    <div class="menu">
      <%= link_to videos_path, class: 'item' do %>
          <i class="youtube icon"></i>
          <b>Видео</b>
      <% end %>

      <%= link_to articles_path, class: 'item' do %>
          <i class="file text outline icon"></i>
          <b>Статьи</b>
      <% end %>

      <%= link_to feedbacks_path, class: 'item' do %>
          <i class="reply all icon"></i>
          <b>Обратная связь</b>
      <% end %>

      <%= link_to messages_path, class: 'item' do %>
          <i class="mail outline icon"></i>
          <b>SMS-сообщения</b>
      <% end %>
    </div>

  </div>
</div>

<%= link_to calendar_index_path, class: 'item' do %>
    <i class="calendar icon"></i>
    Календарь
<% end %>

app/views/shared/_doctor_navbar.html.erb
<%= link_to appointments_path, class: 'item' do %>
  <i class="first aid icon"></i>
  Первичные осмотры
<% end %>

<%= link_to patients_path, class: 'item' do %>
  <i class="users icon"></i>
  Пациенты
<% end %>

<div class="menu">
  <div class="ui dropdown item">
    <i class="dollar icon"></i>
      Прейскурант
    <i class="dropdown icon"></i>

    <div class="menu">
      <%= link_to price_list_categories_path, class: 'item' do %>
        <i class="list layout icon"></i>
        <b>Категории</b>
      <% end %>

      <%= link_to procedures_path, class: 'item' do %>
        <i class="first aid icon"></i>
        <b>Процедуры</b>
      <% end %>

      <%= link_to age_types_path, class: 'item' do %>
        <i class="warning circle icon"></i>
        <b>Возраста</b>
      <% end %>
    </div>

  </div>
</div>

<%= link_to calendar_index_path, class: 'item' do %>
    <i class="calendar icon"></i>
    Календарь
<% end %>

<%= link_to articles_path, class: 'item' do %>
    <i class="file text outline icon"></i>
    Статьи
<% end %>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_semantic.html.erb
<script>
  $( document ).ready(function() {
    $('.ui.checkbox').checkbox();
    $('.ui.dropdown').dropdown();
    $('.ui.accordion').accordion();
    $('.menu .item').tab();
  });
</script>