config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_overriden/registration',
    sessions: 'devise_overriden/session'
  }

  devise_scope :user do
    authenticated :user do
      root 'administration/conditional_appointments#index', as: :root
    end

    unauthenticated do
      root 'landing#index', as: :unauthenticated_root
    end
  end

  get 'article/:id', to: 'administration/articles#show', as: 'show_article'
  get 'conditional_appointments/new',
      to: 'administration/conditional_appointments#new',
      as: 'new_conditional_appointment'

  scope 'admin', module: :administration do
    resources :users, only: [:new, :create]
    resources :patients, except: [:new, :edit] do
      get 'change_status', on: :member

      resources :personal_cards, only: [:index]
    end

    resources :doctors, except: [:new, :edit] do
      get 'manage_status', on: :member
      get 'determine_doctor_time', on: :collection
    end

    resources :appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :conditional_appointments, except: :new do
      get 'change_status', on: :member
    end

    resources :price_list_categories, only: [:index, :create, :update, :destroy]
    resources :age_types, except: [:new, :edit, :show]
    resources :videos, except: :show
    resources :articles, except: :show
    resources :procedures, except: [:new, :edit, :show]

    resources :personal_cards, only: [:edit, :update] do
      get 'history/:id', on: :collection,
                         to: 'personal_cards#history', as: 'history'
    end

    resources :treatments do
      get 'add_primary_fields', on: :collection
      get 'invoice/:treatment_id', on: :collection, to: 'treatments#invoice', as: 'invoice'
      get 'details', on: :member
      get 'manage_state', on: :member
      patch 'manage_treatment_statuses', on: :member
    end

    get 'by_types', to: 'searches#by_types'

    resources :feedbacks, only: [:index, :create] do
      get 'update_status/:id', on: :collection, to: 'feedbacks#update_status', as: :update_status
    end

    resources :calendar, only: :index do
      get 'events', on: :collection
    end
    resources :messages do
      post 'delivery', on: :collection
    end
  end
end

app/models/personal_card.rb
class PersonalCard < ActiveRecord::Base
  belongs_to :patient

  validates_presence_of :patient
end

app/controllers/administration/admin_controller.rb
class Administration::AdminController < ApplicationController
  before_action :authenticate_user

  private

  def authenticate_user
    if current_user.present?
      unless current_user.has_role? :admin or current_user.has_role? :doctor
        redirect_to_root
      end

    elsif current_user.nil?
      redirect_to_root
    end
  end

  def result_redirects(result, path, message)
    if result and message and path
      redirect_to path
      show_result_message message

    elsif message.nil?
      redirect_to path

    elsif path.nil? and message.present?
      redirect_to :back
      show_result_message message
    end
  end

  def redirect_to_root
    redirect_to root_path
    flash[:error] = 'У Вас нет доступа к данной странице'
  end

  def show_result_message message
    message[:success].present? ? flash[:success] = message[:success] : flash[:error] = message[:error]
  end

end

app/controllers/administration/age_types_controller.rb
module Administration
  class AgeTypesController < AdminController

    def index
      @age_types = AgeType.all.order(title: :asc) if AgeType.any?
      @age_type = AgeType.new
    end

    def create
      result = AgeTypes::Create.call(permitted_params: permitted_params)
      result_redirects(result, age_types_path, result.message)
    end
    def new

    end

    def update
      result = AgeTypes::Update.call(
        age_type_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, age_types_path, result.message)
    end

    def destroy
      result = AgeTypes::Destroy.call(age_type_id: params[:id])
      result_redirects(result, age_types_path, result.message)
    end

    private

      def permitted_params
        params.permit :title, :lower_age, :upper_age
      end

  end
end

app/controllers/administration/appointments_controller.rb
module Administration
  class AppointmentsController < AdminController

    def index
      result = Appointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @appointments = result.resources
      @appointment = Appointment.new
      @user = User.new
    end
    def edit
      @appointment = Appointment.find(params[:id])
    end

    def new
      @appointment = Appointment.new
    end

    def create
      result = Appointments::Create.call(permitted_params: permitted_params)
      result_redirects(result, appointments_path, result.message)
    end

    def update
      result = Appointments::Update.call(
        appointment_id: params[:id],
        permitted_params: permitted_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = Appointments::Destroy.call(appointment_id: params[:id])
      result_redirects(result, appointments_path, result.message)
    end

    def change_status
      result = Appointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, appointments_path, result.message)
    end

    private

    def app_params
      params.permit :doctor_id, :patient_id, :appointment_date,
                    :utf8, :authenticity_token, :commit,
                    appointment: [:start_time, :status]
    end

    def permitted_params
      app_params[:appointment].merge(
        doctor_id: params[:doctor_id],
        patient_id: params[:patient_id],
        appointment_date: params[:appointment_date]
      )
    end

  end
end

app/controllers/administration/articles_controller.rb
module Administration
  class ArticlesController < AdminController
    before_action :authenticate_user, except: :show

    def index
      all_articles = current_user.doctor? ? current_user.doctor.articles : Article
      @articles = all_articles.order(created_at: :desc)
      @article = Article.new
    end

    def create
      @article = Article.new article_params
      if @article.save
        redirect_to articles_path
        flash[:success] = 'Статья успешно создана'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при создании статьи'
      end
    end

    def show
      @article = Article.find params[:id]
    end

    def update
      @article = Article.find params[:id]
      if @article.update! article_params
        redirect_to articles_path
        flash[:success] = 'Статья успешно обновлена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при обновлении статьи'
      end
    end

    def destroy
      article = Article.find params[:id]
      if article.destroy
        redirect_to articles_path
        flash[:success] = 'Статья успешно удалена'
      else
        redirect_to :back
        flash[:error] = 'Ошибка при удалении статьи'
      end
    end

    private

    def article_params
      params.permit :title, :content, :doctor_id, :image
    end
  end
end

app/controllers/administration/calendar_controller.rb
module Administration
  class CalendarController < AdminController

    def index
    end

    def events
      if current_user.admin?
        if params[:doctor_id].present?
          @treatments = Treatment.where(doctor_id: params[:doctor_id])
        else
          @treatments = Treatment.where.not(doctor_id: nil)
        end

      elsif current_user.doctor?
        @treatments = current_user.doctor.treatments
      end

      render json: fetch_events
    end

    private

    def fetch_events
      events = []
      @treatments.each do |treatment|
        events.push({
                        title: treatment.patient.fullname + "\n"+ treatment.doctor.fullname,
                        start: treatment.treatment_start,
                        end: treatment.treatment_end,
                        id: treatment.id,
                        backgroundColor: '#CCB0C9',
                        attribute: 'calendar_event'
                    })
      end

      events
    end
  end
end

app/controllers/administration/conditional_appointments_controller.rb
module Administration
  class ConditionalAppointmentsController < AdminController
    before_action :authenticate_user, only: [:index, :edit, :update, :destroy]

    def index
      result = ConditionalAppointments::List.call(
        sort: params[:sort],
        direction: params[:direction],
        page: params[:page],
        current_user: current_user
      )

      @conditional_apps = result.resources
      @appointment = Appointment.new
      @user = User.new
    end

    def new
      @conditional_app = ConditionalAppointment.new
    end

    def edit
      @conditional_app = ConditionalAppointment.find(params[:id])
    end

    def create
      result = ConditionalAppointments::Create.call(permitted_params: conditional_appointment_params)
      result_redirects(result, root_path, result.message)
    end

    def update
      result = ConditionalAppointments::Update.call(
          conditional_app_id: params[:id],
          user_params: user_params,
          patient_params: patient_params,
          appointment_params: appointment_params
      )

      result_redirects(result, appointments_path, result.message)
    end

    def destroy
      result = ConditionalAppointments::Destroy.call(conditional_app_id: params[:id])
      result_redirects(result, conditional_appointments_path, result.message)
    end

    def change_status
      result = ConditionalAppointments::ChangeStatus.call(
        appointment_id: params[:id],
        status: params[:status]
      )

      result_redirects(result, conditional_appointments_path, result.message)
    end

    private

    def permitted_params
      params.permit :name, :surname, :phone, :age, :doctor_id, :appointment_date,
                    :utf8, :authenticity_token, :commit, :action,
                    conditional_appointment: [:start_time, :email]
    end

    def user_params
      {
        'email' => permitted_params[:conditional_appointment][:email],
        'name' => permitted_params[:name],
        'surname' => permitted_params[:surname]
      }
    end

    def patient_params
      {
        'phone' => permitted_params[:phone],
        'age' => permitted_params[:age]
      }
    end

    def appointment_params
      permitted_params[:conditional_appointment].except(:email).
          merge(
              'doctor_id' => permitted_params[:doctor_id],
              'appointment_date' => permitted_params[:appointment_date]
          )
    end

    def conditional_appointment_params
      user_params.merge('phone' => permitted_params[:phone])
    end

  end
end

app/controllers/administration/doctors_controller.rb
module Administration
  class DoctorsController < AdminController

    def index
      result = Doctors::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page]
      )

      @doctors = result.resources
      @doctor = Doctor.new
    end

    def new
      @doctor = Doctor.new
    end

    def edit
      @doctor = Doctor.find(params[:id])
    end

    def show
      @doctor = Doctor.find(params[:id])
      @today_appointments = today_appointments(@doctor)
    end

    def create
      result = Doctors::Create.call(
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def update
      result = Doctors::Update.call(
        doctor_id: params[:id],
        user_params: user_params,
        doctor_params: doctor_params
      )

      result_redirects(result, doctors_path, result.message)
    end

    def destroy
      result = Doctors::Destroy.call(doctor_id: params[:id])
      result_redirects(result, doctors_path, result.message)
    end

    def manage_status
      result = Doctors::ManageStatus.call(
        doctor_id: params[:id],
        work_status: params[:work_status]
      )

      result_redirects(result, doctors_path, result.message)
    end

    def determine_doctor_time
      result = Treatments::DetermineDoctorTime.call(
        doctor_id: params[:doctor_id],
        treatment_date: params[:date]
      )
       
      render json: result.resource
    end

    private

      def permitted_params
        params.permit :name, :surname, :phone,
                      doctor: [:position, :work_history, :work_experience, :work_status,
                               user_attributes: [:email, :avatar, :avatar_cache]]
      end

      def doctor_params
        permitted_params[:doctor].except(:user_attributes).
            merge('phone' => permitted_params[:phone])
      end

      def user_params
        permitted_params[:doctor][:user_attributes].
            merge(
                'name' => permitted_params[:name],
                'surname' => permitted_params[:surname]
            )
      end

      def today_appointments(doctor)
        doctor.appointments.where(appointment_date: :today)
      end

  end
end

app/controllers/administration/feedbacks_controller.rb
module Administration
  class FeedbacksController < AdminController
    skip_before_action :authenticate_user, only: :create

    def index
      @feedbacks = Feedback.all
    end

    def create
      @feedback = Feedback.create(feedback_params)
      if @feedback.save
        flash[:success] = "Ваше сообщение успешно отправлено"
        redirect_to root_path
      else
        flash[:error] = "Вы не заполнили обязательные поля"
        redirect_to root_path + '#contacts'
      end

    end

    def update_status
      @feedback = Feedback.find(params[:id])
      @feedback.update_status!

      redirect_to feedbacks_path
      flash[:success] = "Статус успешно обновлен"
    end

    private

    def feedback_params
      params.permit :name, :phone, :email, :message
    end

  end
end

app/controllers/administration/messages_controller.rb
module Administration
  class MessagesController < AdminController
    include MessagesHelper

    def index
      @message = Message.new
      @messages = Message.all.order(created_at: :desc)
      @patients = Patient.all
    end

    def create
      @message = Message.create(messages_params)
      response = @message.send_custom_sms
      @message.update(sms_id: @message.id.to_s.rjust(7, 'D00000'), send_time: Time.now, status: :sent) if response == '0' || response == '11'
      nikita_response response
      redirect_to messages_path
    end

    def delivery
      patients_ids = params[:patient]
      message = params[:text]
      if patients_ids.include?('all')
        patients = Patient.all
        patients_ids = patients.pluck(:id)
        phones = patients.pluck(:phone)
      else
        phones = Patient.where(id: patients_ids).pluck(:phone)
      end
      @delivery = Delivery.create(patient_ids: patients_ids, message: message)
      if @delivery.save
        response = @delivery.send_delivery_sms phones
        nikita_response response
      end
      redirect_to messages_path
    end

    private

    def messages_params
      params.permit :phone, :text
    end
  end
end

app/controllers/administration/patients_controller.rb
module Administration
  class PatientsController < AdminController

    def index
      result = Patients::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page],
          current_user: current_user
      )

      @patients = result.resources
      @patient = Patient.new
    end

    def show
      @patient = Patient.find(params[:id])

      result = Treatments::List.call(
          sort: params[:sort],
          direction: params[:direction],
          page: params[:page],
          patient: @patient,
          current_user: current_user
      )

      @treatments = result.resources
    end

    def new
      @patient = Patient.new
    end

    def edit
      @patient = Patient.find(params[:id])
    end

    def create
      result = Patients::Create.call(
        user_params: user_params,
        patient_params: patient_params
      )

      result_redirects(result, patients_path, result.message)
    end

    def update
      result = Patients::Update.call(
          patient_id: params[:id],
          patient_params: patient_params,
          user_params: user_params
      )

      result_redirects(result, patients_path, result.message)
    end

    def destroy
      result = Patients::Destroy.call(patient_id: params[:id])
      result_redirects(result, patients_path, result.message)
    end

    def change_status
      result = Patients::ChangeStatus.call(patient_id: params[:id])
      result_redirects(result, patients_path, result.message)
    end

    private

    def permitted_params
      params.permit :phone, :age, :name, :surname,
                    patient: [:gender, user_attributes: [:email, :avatar, :avatar_cache]]
    end

    def patient_params
      permitted_params[:patient].except(:user_attributes).merge(
        'phone' => permitted_params[:phone],
        'age' => permitted_params[:age]
      )
    end

    def user_params
      permitted_params[:patient][:user_attributes].merge(
        'name' => permitted_params[:name],
        'surname' => permitted_params[:surname]
      )
    end

  end
end

app/views/administration/personal_cards/_edit.html.erb
<div class="ui form width changed">
  <%= form_for(@personal_card, html: {class: 'ui equal width form'}) do |f| %>

    <h4 class="ui dividing header">Редактирование амбулаторных данных пациента</h4>

    <div class="field">
      <label>Перенесенные заболевания</label>
      <%= f.text_field :disease, placeholder: 'Укажите заболевания если были таковые' %>
    </div>

    <div class="field">
      <label>Лекарственная или иная аллергия</label>
      <%= f.text_field :allergy, placeholder: 'Укажите при наличии' %>
    </div>

    <div class="field">
      <label>Прием лекарств в настоящее время</label>
      <%= f.text_field :medicine, placeholder: 'Укажите наименования препаратов' %>
    </div>

    <div class="field">
      <label>Кровотечения после хирургических процедур или ранений</label>
      <%= f.text_field :bleeding, placeholder: 'Укажите при наличии' %>
    </div>

    <% if @personal_card.patient.gender == 'female' or @personal_card.patient.gender.nil? %>
      <h5 class="ui dividing header">Для женщин</h5>
      <div class="two fields">
        <div class="field">
          <label>Беременность</label>
          <%= f.select :pregnancy, [['Да', true], ['Нет', false]], {prompt: 'Выберите'},
                         class: 'ui search fluid dropdown' %>
        </div>

        <div class="field">
          <label>Срок беременности</label>
          <%= f.text_field :gestational_age, placeholder: 'Укажите срок' %>
        </div>
      </div>
    <% end %>

    <div class="ui buttons", id="edit_form_style">
      <%= f.submit 'Обновить данные', class: "ui blue button" %>
      <div class="or"></div>
      <%= link_to 'Вернуться к списку', patient_personal_cards_path(@personal_card.patient), class: "negative ui button" %>
    </div>

  <% end %>
</div>

app/views/administration/personal_cards/_modal_for_updating_personal_card.html.erb
<div class="modal fade" id="update_personal_card-<%= @personal_card.id %>" tabindex="-1" role="dialog" aria-labelledby="update_personal_cardLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <%= render partial: 'administration/personal_cards/edit' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="ui gray button" data-dismiss="modal">Выйти</button>
      </div>
    </div>
  </div>
</div>

app/views/administration/personal_cards/_parodontology_cart.html.erb
<%= image_tag("parodontology_cart.jpg", height: '444', width: '750') %>
<h4 class="ui dividing header">Рабочие сокращения</h4>

<div class="two fields">
  <div class="ui grid">
    <div class="seven wide column">
      <div class="ui list" style="margin-left: 15px">
        <div class="item"><b>А</b> - парадонтит (I,II,III,IV)</div>
        <div class="item"><b>С</b> - кариес</div>
        <div class="item"><b>Р</b> - пульпит</div>
        <div class="item"><b>Р*</b> - периодонтит</div>
        <div class="item"><b>Rx</b> - корень</div>
        <div class="item"><b>О</b> - отсутствующий зуб</div>
        <div class="item"><b>П</b> - пломба</div>
        <div class="item"><b>По</b> - несоответствующая требованиям пломба</div>
        <div class="item"><b>К</b> - искусственная коронка</div>
        <div class="item"><b>И</b> - искусственный зуб</div>
        <div class="item"><b>ОД</b> - очаговая деминерализация</div>
      </div>
    </div>

    <div class="five wide column">
      <div class="ui list" style="margin-left: 15px">
        <div class="item"><b>V</b> - витальный</div>
        <div class="item"><b>D</b> - девитальный</div>
        <div class="item"><b>OD</b> - очаговая деминерализация</div>
        <div class="item"><b>F</b> - пломба</div>
        <div class="item"><b>H</b> - пломба</div>
        <div class="item"><b>Rs</b> - реставрация</div>
        <div class="item"><b>Ps</b> - штифт</div>
        <div class="item"><b>Ex</b> - отсутствующий зуб</div>
        <div class="item"><b>K</b> - коронка</div>
        <div class="item"><b>U</b> - искусственный зуб</div>
        <div class="item"><b>MK</b> - коронка "Стомкейр"</div>
      </div>
    </div>
  </div>
</div><br>

app/views/administration/personal_cards/_personal_card_details_listing.html.erb
<div class="treatment_result_points">
  <ol>
    <li><b>Жалобы пациента: </b>
      <div class="complaints">
        <% complaints = treatment.complaint %>
        <%= complaints.present? ? complaints : 'Жалобы не зафиксированы' %>
        <hr>
      </div>
    </li>

    <li><b>Статус до лечения: </b>
      <% if current_user.admin? %>
          <a href="#", data-toggle="modal" data-target="#update_treatment_statuses-<%= treatment.id %>" style="margin-left: 5px">
            <i class="write icon width_color_changed"></i>
          </a>
          <%= render partial: 'administration/treatments/modal_for_updating_treatment_statuses', locals: { treatment: treatment } %>
      <% end %>

      <div class="before_treatment_status">
        <% before_treatment_status = treatment.before_treatment_status %>
        <%= before_treatment_status.present? ? before_treatment_status : 'Не заполнен' %>
        <hr>
      </div>
    </li>

    <li><b>Лечение: </b>
      <% if current_user.admin? %>
          <a href="#", data-toggle="modal" data-target="#update_treatment_statuses-<%= treatment.id %>" style="margin-left: 5px">
            <i class="write icon width_color_changed"></i>
          </a>
          <%= render partial: 'administration/treatments/modal_for_updating_treatment_statuses', locals: { treatment: treatment } %>
      <% end %>

      <div class="treatment_process">
        <% treatment_process = treatment.treatment_process %>
        <%= treatment_process.present? ? treatment_process : 'Не заполнено' %>
        <hr>
      </div>
    </li>
  </ol>
</div><br>

<table class="ui selectable celled table" id="centred_table">
  <tr>
    <th>№</th>
    <th>Доктор</th>
    <th>Процедура</th>
    <th>Зуб</th>
    <th>Стоимость</th>
  </tr>

  <% counter = 0 %>
  <% personal_card_details = TreatmentDetail.hosted_treatments patient, treatment_date: treatment.treatment_date %>

  <% unless personal_card_details.empty? %>
      <% personal_card_details.each do |treatment_detail| %>
          <tr>
            <td class="middle aligned"><%= counter += 1 %></td>
            <td class="middle aligned"><%= treatment_detail.doctor.fullname %></td>
            <td class="middle aligned"><%= treatment_detail.procedure.title %></td>
            <td class="middle aligned"><%= treatment_detail.tooth %></td>
            <td class="middle aligned"><%= "#{treatment_detail.price.to_i.round(0)}" + " сом" %></td>
          </tr>
      <% end %>
  <% end %>
</table>

<h4 class="ui right floated header">
  Общая сумма:
  <%= personal_card_details.sum(:price).to_i %> сом
</h4>

app/views/administration/personal_cards/_personal_information.html.erb
<div class="personal_card_points">
  <ol>
    <li><b>ФИО: </b><%= link_to patient.fullname, patient_path(patient) %></li>
    <li><b>Число, месяц, год рождения: </b></li>
    <li><b>Телефон: </b><%= patient.phone %></li>

    <li><b>Какие из перечисленных заболеваний Вы перенесли: ревматизм, гепатит, туберкулез,
      эндокринные заболевания, ВИЧ, нервные заболевания, сердечнососудистые (гипотония, гипертония),
      другие: </b>
      <div class="diseases">
        <% diseases = patient.personal_card.disease %>
        <%= diseases.present? ? diseases : 'Указанными, либо другими заболеваниями не болел' %>
        <hr>
      </div>
    </li>

    <li><b>Имеется ли у Вас лекарственная или иная аллергия (если есть, то на что)</b>
      <div class="allergy">
        <% allergy = patient.personal_card.allergy %>
        <%= allergy.present? ? allergy : 'Сведений об аллергических реакциях нет' %>
        <hr>
      </div>
    </li>

    <li><b>Принимаете ли Вы какие-либо лекарства в настоящее время</b>
      <div class="medicine">
        <% medicine = patient.personal_card.medicine %>
        <%= medicine.present? ? medicine : 'Нет' %>
        <hr>
      </div>
    </li>

    <li><b>Возникали ли у Вас длительные кровотечения после хирургических процедур или ранений</b>
      <div class="bleeding">
        <% bleeding = patient.personal_card.bleeding %>
        <%= bleeding.present? ? bleeding : 'Нет' %>
        <hr>
      </div>
    </li>

    <% if patient.gender == 'female' or patient.gender.nil? %>
        <li><b>Для женщин. Беременны ли Вы (срок)</b>
          <div class="pregnancy">
            <% pregnancy = patient.personal_card.pregnancy %>
            <%= pregnancy == true ? 'Да' : 'Нет' %>
              <% if patient.personal_card.gestational_age %>
                Срок беременности: <%= patient.personal_card.gestational_age %>
              <% end %>
            <hr>
          </div>
        </li>
    <% end %>
  </ol>
</div>

app/views/administration/personal_cards/index.html.erb
<h3 class="ui left floated header">
  Амбулаторная медицинская карта пациента
</h3>

<div class="ui right floated header">
  <span class="personal_card_updated_date">
    Последнее обновление карты: <%= l @personal_card.updated_at, format: ("%d %B %Y") %>
  </span>

  <% if current_user.admin? %>
      <a href="#", data-toggle="modal" data-target="#update_personal_card-<%= @personal_card.id %>">
        <i class="write icon width_color_changed"></i>
      </a>

      <%= link_to history_personal_cards_path(@personal_card.patient), target: '_blank' do %>
          <i class="file pdf outline icon width_color_changed" style="margin-left: 5px"></i>
      <% end %>
  <% end %>
</div>
<%= render partial: 'administration/personal_cards/modal_for_updating_personal_card' %>

<div class="ui dividing header"></div>

<% patient = @personal_card.patient %>
<div class="ui grid" style="margin-top: 0px">

    <div class="four wide column">
      <div class="ui vertical fluid tabular menu">
        <a class="active item" data-tab="first"><h4>Личные данные</h4></a>
        <a class="item" data-tab="second"><h4>Пародонтальная карта</h4></a>

        <% counter = 0 %>
        <% treatments = hosted_treatments patient %>
        <% treatments.each do |treatment| %>
          <a class="item" data-tab="<%= counter += 1 %>">
            <h4>Прием от <%= l treatment.treatment_date, format: ("%d %B %Y") %></h4>
          </a>
        <% end %>
      </div>
    </div>

    <div class="twelve wide stretched column">
      <div class="ui bottom attached tab active" data-tab="first">
        <%= render partial: 'administration/personal_cards/personal_information', locals: { patient: patient } %>
      </div>

      <div class="ui tab" data-tab="second">
        <%= render partial: 'administration/personal_cards/parodontology_cart' %>
      </div>

      <% counter = 0 %>
      <% treatments.each do |treatment| %>
          <div class="ui tab" data-tab="<%= counter += 1 %>">
            <%= render partial: 'administration/personal_cards/personal_card_details_listing',
                       locals: { patient: patient, treatment: treatment } %>
          </div>
      <% end %>
    </div>
</div>